databases:
  - name: LedgerDB
    plan: free
    databaseName: LedgerDB
    user: admin

services:
  - type: web
    plan: free
    name: Leo_Ledger
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn finance_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: LedgerDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4